In [4]:
import pandas as pd 

# read the datasets 
df1 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2000.csv") 
df2 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2001.csv")  
df3 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2002.csv") 
df4 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2003.csv") 
df5 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2004.csv") 
df6 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2005.csv")  
df7 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2006.csv")  
df8 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2007.csv")  
df9 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2008.csv") 
df10 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2009.csv") 
df11 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2010.csv")  
df12 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2011.csv") 
df13 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2012.csv")  
df14 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2013.csv")  
df15 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2014.csv")  
df16 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2015.csv")  
df17 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2016.csv")  
df18 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2017.csv") 
df19 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2018_2019.csv") 
df20 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2020_2021.csv") 
df21 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2022_2023.csv") 
df22 = pd.read_csv("C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/2024.csv") 

# print the datasets 
print(df1.head()) 
print(df2.head())

                     name    datetime  tempmax  tempmin  temp  feelslikemax  \
0  Wolverhampton, England  2000-01-01     46.6     33.6  40.7          44.5
1  Wolverhampton, England  2000-01-02     50.8     39.3  44.3          50.8
2  Wolverhampton, England  2000-01-03     50.9     38.5  45.9          50.9
3  Wolverhampton, England  2000-01-04     42.4     34.1  37.4          35.9
4  Wolverhampton, England  2000-01-05     52.1     35.1  43.5          52.1

   feelslikemin  feelslike   dew  humidity  ...  solarenergy  uvindex  \
0          33.6       39.8  39.4      95.1  ...          NaN      NaN
1          35.0       40.8  41.2      89.1  ...          NaN      NaN
2          34.2       42.4  42.5      88.2  ...          NaN      NaN
3          27.5       31.6  34.3      88.6  ...          NaN      NaN
4          28.5       37.9  39.1      84.5  ...          NaN      NaN

   severerisk              sunrise               sunset  moonphase  \
0         NaN  2000-01-01T08:19:50  2000-01-01T16:03:54       0.83
1         NaN  2000-01-02T08:19:43  2000-01-02T16:04:59       0.86
2         NaN  2000-01-03T08:19:32  2000-01-03T16:06:07       0.89
3         NaN  2000-01-04T08:19:18  2000-01-04T16:07:17       0.92
4         NaN  2000-01-05T08:19:00  2000-01-05T16:08:30       0.96

               conditions                                        description  \
0  Rain, Partially cloudy  Partly cloudy throughout the day with a chance...
1        Partially cloudy                  Partly cloudy throughout the day.
2  Rain, Partially cloudy  Partly cloudy throughout the day with a chance...
3  Rain, Partially cloudy        Partly cloudy throughout the day with rain.
4  Rain, Partially cloudy  Partly cloudy throughout the day with afternoo...

                icon                                           stations
0               rain  03529099999,03414099999,03520099999,0335409999...
1  partly-cloudy-day  03414099999,03529099999,03520099999,0335409999...
2               rain  03414099999,03529099999,03520099999,0335409999...
3               rain  03414099999,03529099999,03520099999,0335409999...
4               rain  03414099999,03529099999,03520099999,0335409999...

[5 rows x 33 columns]
                     name    datetime  tempmax  tempmin  temp  feelslikemax  \
0  Wolverhampton, England  2001-01-01     49.5     38.8  45.3          44.9
1  Wolverhampton, England  2001-01-02     48.1     42.9  46.2          43.7
2  Wolverhampton, England  2001-01-03     45.9     35.4  41.1          42.7
3  Wolverhampton, England  2001-01-04     46.6     37.6  44.1          45.0
4  Wolverhampton, England  2001-01-05     42.0     34.5  38.1          42.0

   feelslikemin  feelslike   dew  humidity  ...  solarenergy  uvindex  \
0          31.4       40.4  42.2      88.9  ...          NaN      NaN
1          37.2       41.2  42.7      87.6  ...          NaN      NaN
2          29.0       35.5  36.6      84.1  ...          NaN      NaN
3          36.5       41.7  41.4      90.3  ...          NaN      NaN
4          32.4       37.5  36.6      94.4  ...          NaN      NaN

   severerisk              sunrise               sunset  moonphase  \
0         NaN  2001-01-01T08:19:46  2001-01-01T16:04:43       0.22
1         NaN  2001-01-02T08:19:36  2001-01-02T16:05:50       0.25
2         NaN  2001-01-03T08:19:22  2001-01-03T16:07:00       0.29
3         NaN  2001-01-04T08:19:05  2001-01-04T16:08:12       0.32
4         NaN  2001-01-05T08:18:45  2001-01-05T16:09:27       0.36

               conditions                                        description  \
0  Rain, Partially cloudy        Partly cloudy throughout the day with rain.
1  Rain, Partially cloudy  Partly cloudy throughout the day with a chance...
2  Rain, Partially cloudy        Partly cloudy throughout the day with rain.
3  Rain, Partially cloudy  Partly cloudy throughout the day with a chance...
4  Rain, Partially cloudy        Partly cloudy throughout the day with rain.

   icon                                         stations
0  rain  03414099999,03529099999,03520099999,03544099999
1  rain  03414099999,03529099999,03520099999,03544099999
2  rain  03414099999,03529099999,03520099999,03544099999
3  rain  03414099999,03529099999,03520099999,03544099999
4  rain  03414099999,03529099999,03520099999,03544099999

[5 rows x 33 columns]

In [5]:
concat_data = pd.concat([df1, df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,
                         df14,df15,df16,df17,df18,df19,df20,df21,df22,], ignore_index=True) 
print(concat_data)

                        name    datetime  tempmax  tempmin  temp  \
0     Wolverhampton, England  2000-01-01     46.6     33.6  40.7
1     Wolverhampton, England  2000-01-02     50.8     39.3  44.3
2     Wolverhampton, England  2000-01-03     50.9     38.5  45.9
3     Wolverhampton, England  2000-01-04     42.4     34.1  37.4
4     Wolverhampton, England  2000-01-05     52.1     35.1  43.5
...                      ...         ...      ...      ...   ...
8838  Wolverhampton, England  2024-04-12     63.8     49.0  56.0
8839  Wolverhampton, England  2024-04-13     59.0     47.5  53.0
8840  Wolverhampton, England  2024-04-14     54.2     40.4  48.0
8841  Wolverhampton, England  2024-04-15     48.8     44.3  46.2
8842  Wolverhampton, England  2024-04-16     53.0     40.8  47.1

      feelslikemax  feelslikemin  feelslike   dew  humidity  ...  solarenergy  \
0             44.5          33.6       39.8  39.4      95.1  ...          NaN
1             50.8          35.0       40.8  41.2      89.1  ...          NaN
2             50.9          34.2       42.4  42.5      88.2  ...          NaN
3             35.9          27.5       31.6  34.3      88.6  ...          NaN
4             52.1          28.5       37.9  39.1      84.5  ...          NaN
...            ...           ...        ...   ...       ...  ...          ...
8838          63.8          44.6       55.5  47.2      73.4  ...         10.7
8839          59.0          44.3       52.3  46.9      80.0  ...         10.8
8840          54.2          37.2       45.8  37.8      68.7  ...         14.1
8841          42.1          37.1       39.4  38.3      74.4  ...         14.1
8842          53.0          37.0       43.2  39.5      75.1  ...         12.0

      uvindex  severerisk              sunrise               sunset  \
0         NaN         NaN  2000-01-01T08:19:50  2000-01-01T16:03:54
1         NaN         NaN  2000-01-02T08:19:43  2000-01-02T16:04:59
2         NaN         NaN  2000-01-03T08:19:32  2000-01-03T16:06:07
3         NaN         NaN  2000-01-04T08:19:18  2000-01-04T16:07:17
4         NaN         NaN  2000-01-05T08:19:00  2000-01-05T16:08:30
...       ...         ...                  ...                  ...
8838      4.0         NaN  2024-04-12T06:16:25  2024-04-12T20:03:05
8839      6.0         NaN  2024-04-13T06:14:10  2024-04-13T20:04:50
8840      8.0         NaN  2024-04-14T06:11:56  2024-04-14T20:06:35
8841      7.0         NaN  2024-04-15T06:09:42  2024-04-15T20:08:21
8842     10.0         NaN  2024-04-16T06:07:29  2024-04-16T20:10:06

      moonphase              conditions  \
0          0.83  Rain, Partially cloudy
1          0.86        Partially cloudy
2          0.89  Rain, Partially cloudy
3          0.92  Rain, Partially cloudy
4          0.96  Rain, Partially cloudy
...         ...                     ...
8838       0.12        Partially cloudy
8839       0.15  Rain, Partially cloudy
8840       0.19        Partially cloudy
8841       0.25  Rain, Partially cloudy
8842       0.25  Rain, Partially cloudy

                                            description               icon  \
0     Partly cloudy throughout the day with a chance...               rain
1                     Partly cloudy throughout the day.  partly-cloudy-day
2     Partly cloudy throughout the day with a chance...               rain
3           Partly cloudy throughout the day with rain.               rain
4     Partly cloudy throughout the day with afternoo...               rain
...                                                 ...                ...
8838                  Partly cloudy throughout the day.  partly-cloudy-day
8839        Partly cloudy throughout the day with rain.               rain
8840                  Partly cloudy throughout the day.  partly-cloudy-day
8841  Partly cloudy throughout the day with a chance...               rain
8842  Partly cloudy throughout the day with a chance...               rain

                                               stations
0     03529099999,03414099999,03520099999,0335409999...
1     03414099999,03529099999,03520099999,0335409999...
2     03414099999,03529099999,03520099999,0335409999...
3     03414099999,03529099999,03520099999,0335409999...
4     03414099999,03529099999,03520099999,0335409999...
...                                                 ...
8838  03414099999,03529099999,03330099999,0353509999...
8839  03414099999,03529099999,03520099999,0333009999...
8840  03414099999,03529099999,03520099999,0333009999...
8841  03414099999,03529099999,03520099999,0333009999...
8842  03414099999,03529099999,03520099999,0333009999...

[8843 rows x 33 columns]

In [6]:
# Save to CSV file
concat_data.to_csv('weatherdata.csv', index=False)

In [8]:
concat_data.to_csv('C:/Users/Uche Buzz/Desktop/School stuff/Final Project/Datasets/weatherdata.csv', index=False)

In [9]:
concat_data.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Wolverhampton, England",2000-01-01,46.6,33.6,40.7,44.5,33.6,39.8,39.4,95.1,...,NaN,NaN,NaN,2000-01-01T08:19:50,2000-01-01T16:03:54,0.83,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"03529099999,03414099999,03520099999,0335409999..."
1,"Wolverhampton, England",2000-01-02,50.8,39.3,44.3,50.8,35.0,40.8,41.2,89.1,...,NaN,NaN,NaN,2000-01-02T08:19:43,2000-01-02T16:04:59,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"03414099999,03529099999,03520099999,0335409999..."
2,"Wolverhampton, England",2000-01-03,50.9,38.5,45.9,50.9,34.2,42.4,42.5,88.2,...,NaN,NaN,NaN,2000-01-03T08:19:32,2000-01-03T16:06:07,0.89,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"03414099999,03529099999,03520099999,0335409999..."
3,"Wolverhampton, England",2000-01-04,42.4,34.1,37.4,35.9,27.5,31.6,34.3,88.6,...,NaN,NaN,NaN,2000-01-04T08:19:18,2000-01-04T16:07:17,0.92,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"03414099999,03529099999,03520099999,0335409999..."
4,"Wolverhampton, England",2000-01-05,52.1,35.1,43.5,52.1,28.5,37.9,39.1,84.5,...,NaN,NaN,NaN,2000-01-05T08:19:00,2000-01-05T16:08:30,0.96,"Rain, Partially cloudy",Partly cloudy throughout the day with afternoo...,rain,"03414099999,03529099999,03520099999,0335409999..."